### ISSUE TITLE
How to trigger the completion ?

### ISSUE THREAD

**Issue by teto** [paretje/deoplete-notmuch#1]
First I hope you don't mind but I've added this source to https://github.com/Shougo/deoplete.nvim/wiki/Completion-Sources. I was really annoyed that I couldn't find a deoplete+notmuch plugin so you made my day !

Admittingly I don't know much about vim completion but I wondered how the autocompletion was triggered ?
 it seems I don't have omnifunc setup ( E764: option 'completefunc' is not enabled), and I only manage to see the mail completion when typing "To: " then waiting. Seems like it only completes on lines starting with To/Cc etc https://github.com/paretje/deoplete-notmuch/blob/9d54bc5799e680bda824e5519d5a0e8c3d87454d/rplugin/python3/deoplete/sources/notmuch.py#L10 . Is there anyway to force the popup menu/deoplete completions to appear ?

Also I wonder if the 'tag:sent' is a good default. I don't seem to have this tag here so maybe tag:inbox would be best (and it can be overwritten in vimrc)

**Comment by paretje** [comment]
I'm sorry for the late reply, I forgot about the issue, sorry.

This is a deoplete source. While deoplete supports `omnifunc` as a source of completions, it's normal `omnifunc` isn't set.

It's intended behaviour that by default, the completion is only triggered in email headers, but it should be possible to force completion with `deoplete#manual_complete()`. However, that won't work at the moment. I'll try to fix that.

About the default filter: I personally prefer `tag:sent` as to exclude any notification mails and only use addresses I actually sent a mail to. But maybe `tag:inbox` should be used as a more common default.

**Comment by teto** [comment]
thanks
