### ISSUE TITLE
I could not get the autocomplete to work for mail addresses

### ISSUE THREAD

**Issue by Lattitude75** [paretje/deoplete-notmuch#6]
I was very happy to find notmuch with deoplete. A huge thumbs-up for the work!

I installed deoplete-notmuch in nvim and have done the UpdateRemotePlugins and PlugInstall. But, the autocomplete does not work for mail addresses. I checked that the format for the addresses from notmuch is correct and in the json format as needed by the plugin. Still, it just does not give me any auto completions.

I have the following [deoplete log](https://github.com/Lattitude75/Temporary/blob/master/deoplete.log). 
Please help me out here.

I will provide any more information if necessary

**Comment by paretje** [comment]
The completion source is only enabled for the `mail` filetype by default. Judging from the log, you don't have a filetype set. You'll have to use the mail filetype, or enable the source for all filetypes.

**Comment by Lattitude75** [comment]
Yes, I got it to work for an .eml file. Seems like the email client I use, Astroid, does not seem to make the draft in one of the mail filetypes.

Thank you for your time!

**Comment by paretje** [comment]
Seems like it uses the `.mail` extension. In that case, you can also add something like this to your vimrc:
```vim
au BufRead,BufNewFile *.mail setfiletype mail
```
